name: Update Advisory

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'advisories/**'
    - 'docs/**'
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *' # Run every day at midnight

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: '1.24.1'
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Run tests
      run: go test -v ./src/...
      continue-on-error: false
    - name: Run Go application
      run: |
        go run src/main.go

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./advisories/V8-advisory.json
        git add ./src/V8-cache.json
        git commit -m "Update advisories/V8_advisory.json and src/V8-cache.json"
        git push
